name: project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  animated_widgets: ^1.1.0
  flutter_animate: ^4.0.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.2.5
  http: ^1.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/carbon_credit.png